import PrintLayout from '@/components/print/PrintLayout'
import { toDateInputValue } from '@/utils/contractDuration'
import { formatCurrency } from '@/utils/formatCurrency'

const FinanceExpensePrint = ({ expense, setup, locale }) => (
  <PrintLayout title='PAYMENT / EXPENSE VOUCHER' documentNumber={expense.id} date={toDateInputValue(expense.expense_date)} setup={setup} recipientLabel='Prepared / Spent By' recipientName={expense.spent_by?.full_name} authorizedName={setup?.signatory_name} authorizedTitle='Approved By / Finance Director' labels={{ authorizedRepresentative: 'Approved By / Finance Director', recipientSignature: 'Prepared / Spent By' }}>
    <div className='space-y-6 text-xs'>
      <section><h2 className='enterprise-section-title'>Expense Details</h2><div className='grid grid-cols-2 gap-4'>{[['Paid / Spent By', expense.spent_by?.full_name || 'N/A'], ['Payment Method', expense.payment_method?.label || 'Cash'], ['Expense Category', expense.expense_type?.label || 'N/A'], ['Project Charge', expense.project?.title || 'General Overhead']].map(([label, value]) => <div key={label} className='rounded border border-gray-200 bg-gray-50/50 p-3'><p className='text-[10px] font-semibold uppercase text-gray-500'>{label}</p><p className='mt-1 font-semibold text-gray-800'>{value}</p></div>)}</div></section>
      <section><h2 className='enterprise-section-title'>Line Item Particulars</h2><table className='w-full border-collapse'><thead><tr className='bg-gray-50'><th className='border border-gray-200 p-2 text-start'>Particulars / Description</th><th className='border border-gray-200 p-2 text-end'>Quantity</th><th className='border border-gray-200 p-2 text-end'>Unit Price</th><th className='border border-gray-200 p-2 text-end'>Sub Total</th></tr></thead><tbody><tr><td className='border border-gray-200 p-2'>{expense.details}</td><td className='border border-gray-200 p-2 text-end'>{expense.quantity}</td><td className='border border-gray-200 p-2 text-end'>{formatCurrency(expense.unit_price, locale, expense.currency)}</td><td className='border border-gray-200 p-2 text-end font-semibold'>{formatCurrency(expense.sub_total, locale, expense.currency)}</td></tr></tbody></table></section>
      <section className='ml-auto w-full max-w-[92mm] rounded border border-gray-200 text-xs'><div className='flex justify-between border-b border-gray-200 p-2'><span>Subtotal</span><strong>{formatCurrency(expense.sub_total, locale, expense.currency)}</strong></div><div className='flex justify-between border-b border-gray-200 p-2'><span>Base Equivalent</span><strong>{formatCurrency(expense.amount_base, locale, setup?.currency_code || 'AFN')} (Rate: {expense.exchange_rate})</strong></div><div className='flex justify-between p-2 text-sm'><strong>TOTAL DISBURSED</strong><strong>{formatCurrency(expense.sub_total, locale, expense.currency)}</strong></div></section>
      <section className='grid grid-cols-3 gap-3 text-center text-[11px]'><div className='border border-gray-200 p-3'>Prepared / Spent By<br /><strong>{expense.spent_by?.full_name || '—'}</strong></div><div className='border border-gray-200 p-3'>Verified / Accountant</div><div className='border border-gray-200 p-3'>Approved By / Finance Director</div></section>
    </div>
  </PrintLayout>
)

export default FinanceExpensePrint
